services:
  core:
    build:
      context: ../
      dockerfile: docker/core.Dockerfile
    container_name: okoshki-core-service
    restart: always
    env_file:
      - ../.env.${APP_ENV:-dev}
    environment:
      - CONFIG_FILE=config.${APP_ENV:-dev}
    volumes:
      - ../config:/config:ro
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

  db:
    image: postgres:15-alpine
    container_name: okoshki-postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-dev_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-dev_password}
      POSTGRES_DB: ${DB_NAME:-okoshki_db}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-dev_user} -d ${DB_NAME:-okoshki_db}"]
      interval: 2s
      timeout: 5s
      retries: 10

  migrate:
    image: migrate/migrate
    container_name: okoshki-migrate
    volumes:
      - ../migrations:/migrations
    command: [ "-path", "/migrations", "-database", "postgres://${DB_USER:-dev_user}:${DB_PASSWORD:-dev_password}@db:5432/${DB_NAME:-okoshki_db}?sslmode=disable", "up" ]
    depends_on:
      db:
        condition: service_healthy

  nginx:
    build:
      context: ../
      dockerfile: docker/nginx.Dockerfile
    container_name: okoshki-nginx-frontend
    restart: always
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ../.env.${APP_ENV:-dev}
    volumes:
      - ${FRONT_PATH}:/usr/share/nginx/html:ro
      - ../nginx/certs:/etc/letsencrypt:ro        # Здесь будут лежать ключи
      - ../nginx/www:/var/www/certbot:ro          # Папка для проверки домена
    
    depends_on:
      - core
  
  certbot:
    image: certbot/certbot
    container_name: okoshki-certbot
    volumes:
      - ../nginx/certs:/etc/letsencrypt           # Пишет ключи сюда
      - ../nginx/www:/var/www/certbot             # Пишет файлы проверки сюда
    entrypoint: >
      /bin/sh -c "trap exit TERM;
      certbot certonly --webroot -w /var/www/certbot
      --email safonov.300@yandex.ru --agree-tos --no-eff-email
      -d okoski.ru -d www.okoski.ru --keep-until-expiring;
      while :; do 
        certbot renew; 
        sleep 12h & wait $${!}; 
      done"
    restart: unless-stopped
    depends_on:
      - nginx

volumes:
  pg_data: