version: "3"
dotenv: [".env.dev"]
# Глобальные переменные проекта
vars:
  GO_VERSION: "1.26"
  GOLANGCI_LINT_VERSION: "v2.8.0"
  GCI_VERSION: "v0.13.7"
  GOFUMPT_VERSION: "v0.9.2"

  BIN_DIR: "{{.ROOT_DIR}}/bin"
  GOLANGCI_LINT: "{{.BIN_DIR}}/golangci-lint"
  GCI: "{{.BIN_DIR}}/gci"
  GOFUMPT: "{{.BIN_DIR}}/gofumpt"

  DOMAIN: okoski.ru
  CERT_DIR: ./nginx/certs/live/{{.DOMAIN}}

tasks:
  install-formatters:
    desc: "Устанавливает форматтеры gci и gofumpt в ./bin"
    cmds:
      - |
        [ -f {{.GOFUMPT}} ] || {
          echo '📦 Устанавливаем gofumpt {{.GOFUMPT_VERSION}}...'
          GOBIN={{.BIN_DIR}} go install mvdan.cc/gofumpt@{{.GOFUMPT_VERSION}}
        }
        [ -f {{.GCI}} ] || {
          echo '📦 Устанавливаем gci {{.GCI_VERSION}}...'
          GOBIN={{.BIN_DIR}} go install github.com/daixiang0/gci@{{.GCI_VERSION}}
        }
    status:
      - test -x {{.GOFUMPT}}
      - test -x {{.GCI}}

  format:
    desc: "Форматирует весь проект gofumpt + gci"
    deps: [install-formatters]
    cmds:
      - |
        echo "🧼 Форматируем через gofumpt ..."
        find . -type f -name '*.go' ! -path '*/mocks/*' -exec {{.GOFUMPT}} -extra -w {} +
      - |
        echo "🎯 Сортируем импорты через gci ..."
        find . -type f -name '*.go' ! -path '*/mocks/*' -exec {{.GCI}} write -s standard -s default -s "prefix(github.com/RBS-Team/Okoshki/)" {} +

  install-golangci-lint:
    desc: "Устанавливает golangci-lint в каталог bin"
    cmds:
      - |
        [ -f {{.GOLANGCI_LINT}} ] || {
          mkdir -p {{.BIN_DIR}}
          echo "📦 Устанавливаем golangci-lint {{.GOLANGCI_LINT_VERSION}}..."
          GOBIN={{.BIN_DIR}} go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}}
        }
    status:
      - test -x {{.GOLANGCI_LINT}}

  lint:
    desc: "Запускает golangci-lint для всех модулей"
    deps: [install-golangci-lint]
    cmds:
      - "{{.GOLANGCI_LINT}} run ./... --config=.golangci.yml"

  generate:
    aliases:
      - gen
    desc: "Generate code from proto files"
    cmds:
      - protoc -I proto proto/sso/*.proto --go_out=./proto --go_opt=paths=source_relative --go-grpc_out=./proto --go-grpc_opt=paths=source_relative

  env-up:
    desc: "Поднимает докер с БД для сервиса core"
    cmds:
      - docker compose -f deployments/docker-compose.yaml up -d db

  env-down:
    cmds:
      - docker compose -f deployments/docker-compose.yaml down db

  migrate-create:
    silent: true
    vars:
      seq: "{{.seq}}"
    cmds:
      - |
        if [ -z "{{.seq}}" ]; then
          echo "Отсутствует необходимый параметр seq. Пример: task migrate-create seq=init";
          exit 1;
        fi;
        docker compose -f deployments/docker-compose.yaml run --rm migrate create -ext sql -dir /migrations -seq {{.seq}}

  migrate-up:
    cmds:
      - task: migrate-action
        vars:
          action: up

  migrate-down:
    cmds:
      - task: migrate-action
        vars:
          action: down

  migrate-action:
    silent: true
    cmds:
      - |
        if [ -z "{{.action}}" ]; then
          echo "Отсутствует необходимый параметр action. Пример: task migrate-action action=up";
          exit 1;
        fi;
        docker compose -f deployments/docker-compose.yaml run --rm migrate \
        -path /migrations \
        -database "postgres://{{.DB_USER}}:{{.DB_PASSWORD}}@db:5432/{{.DB_NAME}}?sslmode=disable" \
        {{.action}}

  swager:
    cmds:
      - swag init -g cmd/core/main.go
      - echo "Дергать ручки можно http://localhost:8080/swagger/index.html"
    desc: "Апишка, которую можно потестировать в UI"

  up:
    desc: "Запускает проект (билд + старт контейнеров) с подробным выводом"
    cmds:
      - docker compose -f deployments/docker-compose.yaml --env-file .env.prod build --progress=plain
      - docker compose -f deployments/docker-compose.yaml --env-file .env.prod up -d

  stop:
    desc: "Останавливает контейнеры"
    cmds:
      - docker compose -f deployments/docker-compose.yaml --env-file .env.dev stop

  down:
    desc: "Удаляет контейнеры и сети"
    cmds:
      - docker compose -f deployments/docker-compose.yaml --env-file .env.dev down

  # Эту команду запускать только если ХОЧЕШЬ очистить базу именно этого проекта
  reset-db:
    desc: "ВНИМАНИЕ: Полная очистка БД текущего проекта"
    cmds:
      - docker compose -f deployments/docker-compose.yaml --env-file .env.dev down -v

  logs:
    desc: "Логи сервиса"
    cmds:
      - docker logs -f okoshki-core

  ps:
    desc: "Статус контейнеров"
    cmds:
      - docker compose -f deployments/docker-compose.yaml ps

  init:
    desc: "Первый запуск с генерацией SSL пустышек"
    cmds:
      - echo "---Подготавливаю временные сертификаты---"
      - mkdir -p {{.CERT_DIR}}
      - |
        if [ ! -f {{.CERT_DIR}}/fullchain.pem ]; then
          openssl req -x509 -nodes -newkey rsa:2048 -days 1 \
            -keyout {{.CERT_DIR}}/privkey.pem \
            -out {{.CERT_DIR}}/fullchain.pem \
            -subj "/CN=localhost"
          touch {{.CERT_DIR}}/chain.pem
        fi
      - echo "--- Запускаю контейнеры с помощью task up ---"
      - task: up
      - echo "--- Запрашиваю реальные сертификаты ---"
      - docker compose -f deployments/docker-compose.yaml --env-file .env.prod stop certbot
      - |
        docker compose -f deployments/docker-compose.yaml --env-file .env.prod run --rm certbot certonly --webroot -w /var/www/certbot \
          --email {{.EMAIL}} --agree-tos --no-eff-email \
          -d {{.DOMAIN}} -d www.{{.DOMAIN}}
      - docker compose -f deployments/docker-compose.yaml --env-file .env.prod start certbot
      - echo "--- Перезагружаю Nginx ---"
      - docker compose -f deployments/docker-compose.yaml --env-file .env.prod exec nginx nginx -s reload
    status:
      # Команда не будет запускаться повторно, если реальный сертификат уже есть
      - test -f {{.CERT_DIR}}/fullchain.pem && openssl x509 -checkend 86400 -noout -in {{.CERT_DIR}}/fullchain.pem
