// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson2f096870DecodeGithubComRBSTeamOkoshkiMicroservicesCoreReviewsDto(in *jlexer.Lexer, out *ReviewResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "client_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ClientID = string(in.String())
			}
		case "master_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MasterID = string(in.String())
			}
		case "appointment_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AppointmentID = string(in.String())
			}
		case "rating":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Rating = int(in.Int())
			}
		case "comment":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Comment = string(in.String())
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2f096870EncodeGithubComRBSTeamOkoshkiMicroservicesCoreReviewsDto(out *jwriter.Writer, in ReviewResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"client_id\":"
		out.RawString(prefix)
		out.String(string(in.ClientID))
	}
	{
		const prefix string = ",\"master_id\":"
		out.RawString(prefix)
		out.String(string(in.MasterID))
	}
	{
		const prefix string = ",\"appointment_id\":"
		out.RawString(prefix)
		out.String(string(in.AppointmentID))
	}
	{
		const prefix string = ",\"rating\":"
		out.RawString(prefix)
		out.Int(int(in.Rating))
	}
	{
		const prefix string = ",\"comment\":"
		out.RawString(prefix)
		out.String(string(in.Comment))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ReviewResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2f096870EncodeGithubComRBSTeamOkoshkiMicroservicesCoreReviewsDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ReviewResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2f096870EncodeGithubComRBSTeamOkoshkiMicroservicesCoreReviewsDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ReviewResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2f096870DecodeGithubComRBSTeamOkoshkiMicroservicesCoreReviewsDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ReviewResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2f096870DecodeGithubComRBSTeamOkoshkiMicroservicesCoreReviewsDto(l, v)
}
func easyjson2f096870DecodeGithubComRBSTeamOkoshkiMicroservicesCoreReviewsDto1(in *jlexer.Lexer, out *CreateReviewRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "appointment_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AppointmentID = string(in.String())
			}
		case "rating":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Rating = int(in.Int())
			}
		case "comment":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Comment = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2f096870EncodeGithubComRBSTeamOkoshkiMicroservicesCoreReviewsDto1(out *jwriter.Writer, in CreateReviewRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"appointment_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.AppointmentID))
	}
	{
		const prefix string = ",\"rating\":"
		out.RawString(prefix)
		out.Int(int(in.Rating))
	}
	{
		const prefix string = ",\"comment\":"
		out.RawString(prefix)
		out.String(string(in.Comment))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateReviewRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2f096870EncodeGithubComRBSTeamOkoshkiMicroservicesCoreReviewsDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateReviewRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2f096870EncodeGithubComRBSTeamOkoshkiMicroservicesCoreReviewsDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateReviewRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2f096870DecodeGithubComRBSTeamOkoshkiMicroservicesCoreReviewsDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateReviewRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2f096870DecodeGithubComRBSTeamOkoshkiMicroservicesCoreReviewsDto1(l, v)
}
