// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson41838e95DecodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto(in *jlexer.Lexer, out *GetAvailableSlotsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "slots":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Slots = make(map[string][]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v1 []string
					if in.IsNull() {
						in.Skip()
						v1 = nil
					} else {
						in.Delim('[')
						if v1 == nil {
							if !in.IsDelim(']') {
								v1 = make([]string, 0, 4)
							} else {
								v1 = []string{}
							}
						} else {
							v1 = (v1)[:0]
						}
						for !in.IsDelim(']') {
							var v2 string
							if in.IsNull() {
								in.Skip()
							} else {
								v2 = string(in.String())
							}
							v1 = append(v1, v2)
							in.WantComma()
						}
						in.Delim(']')
					}
					(out.Slots)[key] = v1
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson41838e95EncodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto(out *jwriter.Writer, in GetAvailableSlotsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"slots\":"
		out.RawString(prefix[1:])
		if in.Slots == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v3First := true
			for v3Name, v3Value := range in.Slots {
				if v3First {
					v3First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v3Name))
				out.RawByte(':')
				if v3Value == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
					out.RawString("null")
				} else {
					out.RawByte('[')
					for v4, v5 := range v3Value {
						if v4 > 0 {
							out.RawByte(',')
						}
						out.String(string(v5))
					}
					out.RawByte(']')
				}
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetAvailableSlotsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson41838e95EncodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetAvailableSlotsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson41838e95EncodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetAvailableSlotsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson41838e95DecodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetAvailableSlotsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson41838e95DecodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto(l, v)
}
func easyjson41838e95DecodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto1(in *jlexer.Lexer, out *CreateAppointmentRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "service_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ServiceID = string(in.String())
			}
		case "start_at":
			if in.IsNull() {
				in.Skip()
			} else {
				out.StartAt = string(in.String())
			}
		case "client_comment":
			if in.IsNull() {
				in.Skip()
				out.ClientComment = nil
			} else {
				if out.ClientComment == nil {
					out.ClientComment = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.ClientComment = string(in.String())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson41838e95EncodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto1(out *jwriter.Writer, in CreateAppointmentRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"service_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ServiceID))
	}
	{
		const prefix string = ",\"start_at\":"
		out.RawString(prefix)
		out.String(string(in.StartAt))
	}
	if in.ClientComment != nil {
		const prefix string = ",\"client_comment\":"
		out.RawString(prefix)
		out.String(string(*in.ClientComment))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateAppointmentRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson41838e95EncodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateAppointmentRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson41838e95EncodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateAppointmentRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson41838e95DecodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateAppointmentRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson41838e95DecodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto1(l, v)
}
func easyjson41838e95DecodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto2(in *jlexer.Lexer, out *AppointmentResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "client_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ClientID = string(in.String())
			}
		case "master_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MasterID = string(in.String())
			}
		case "service_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ServiceID = string(in.String())
			}
		case "start_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.StartAt).UnmarshalJSON(data))
				}
			}
		case "end_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.EndAt).UnmarshalJSON(data))
				}
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "client_comment":
			if in.IsNull() {
				in.Skip()
				out.ClientComment = nil
			} else {
				if out.ClientComment == nil {
					out.ClientComment = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.ClientComment = string(in.String())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson41838e95EncodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto2(out *jwriter.Writer, in AppointmentResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"client_id\":"
		out.RawString(prefix)
		out.String(string(in.ClientID))
	}
	{
		const prefix string = ",\"master_id\":"
		out.RawString(prefix)
		out.String(string(in.MasterID))
	}
	{
		const prefix string = ",\"service_id\":"
		out.RawString(prefix)
		out.String(string(in.ServiceID))
	}
	{
		const prefix string = ",\"start_at\":"
		out.RawString(prefix)
		out.Raw((in.StartAt).MarshalJSON())
	}
	{
		const prefix string = ",\"end_at\":"
		out.RawString(prefix)
		out.Raw((in.EndAt).MarshalJSON())
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	if in.ClientComment != nil {
		const prefix string = ",\"client_comment\":"
		out.RawString(prefix)
		out.String(string(*in.ClientComment))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AppointmentResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson41838e95EncodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AppointmentResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson41838e95EncodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AppointmentResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson41838e95DecodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AppointmentResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson41838e95DecodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto2(l, v)
}
