// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonF3eb2881DecodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto(in *jlexer.Lexer, out *UpdateAppointmentStatusRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "master_note":
			if in.IsNull() {
				in.Skip()
				out.MasterNote = nil
			} else {
				if out.MasterNote == nil {
					out.MasterNote = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.MasterNote = string(in.String())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF3eb2881EncodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto(out *jwriter.Writer, in UpdateAppointmentStatusRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix[1:])
		out.String(string(in.Status))
	}
	if in.MasterNote != nil {
		const prefix string = ",\"master_note\":"
		out.RawString(prefix)
		out.String(string(*in.MasterNote))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UpdateAppointmentStatusRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF3eb2881EncodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UpdateAppointmentStatusRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF3eb2881EncodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UpdateAppointmentStatusRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF3eb2881DecodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UpdateAppointmentStatusRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF3eb2881DecodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto(l, v)
}
func easyjsonF3eb2881DecodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto1(in *jlexer.Lexer, out *MasterAppointmentView) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "client_id":
			if in.IsNull() {
				in.Skip()
				out.ClientID = nil
			} else {
				if out.ClientID == nil {
					out.ClientID = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.ClientID = string(in.String())
				}
			}
		case "client_email":
			if in.IsNull() {
				in.Skip()
				out.ClientEmail = nil
			} else {
				if out.ClientEmail == nil {
					out.ClientEmail = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.ClientEmail = string(in.String())
				}
			}
		case "client_avatar":
			if in.IsNull() {
				in.Skip()
				out.ClientAvatar = nil
			} else {
				if out.ClientAvatar == nil {
					out.ClientAvatar = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.ClientAvatar = string(in.String())
				}
			}
		case "service_id":
			if in.IsNull() {
				in.Skip()
				out.ServiceID = nil
			} else {
				if out.ServiceID == nil {
					out.ServiceID = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.ServiceID = string(in.String())
				}
			}
		case "service_title":
			if in.IsNull() {
				in.Skip()
				out.ServiceTitle = nil
			} else {
				if out.ServiceTitle == nil {
					out.ServiceTitle = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.ServiceTitle = string(in.String())
				}
			}
		case "price":
			if in.IsNull() {
				in.Skip()
				out.Price = nil
			} else {
				if out.Price == nil {
					out.Price = new(float64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Price = float64(in.Float64())
				}
			}
		case "duration_minutes":
			if in.IsNull() {
				in.Skip()
				out.Duration = nil
			} else {
				if out.Duration == nil {
					out.Duration = new(int)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Duration = int(in.Int())
				}
			}
		case "start_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.StartAt).UnmarshalJSON(data))
				}
			}
		case "end_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.EndAt).UnmarshalJSON(data))
				}
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "is_manual_block":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsManualBlock = bool(in.Bool())
			}
		case "client_comment":
			if in.IsNull() {
				in.Skip()
				out.ClientComment = nil
			} else {
				if out.ClientComment == nil {
					out.ClientComment = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.ClientComment = string(in.String())
				}
			}
		case "master_note":
			if in.IsNull() {
				in.Skip()
				out.MasterNote = nil
			} else {
				if out.MasterNote == nil {
					out.MasterNote = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.MasterNote = string(in.String())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF3eb2881EncodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto1(out *jwriter.Writer, in MasterAppointmentView) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	if in.ClientID != nil {
		const prefix string = ",\"client_id\":"
		out.RawString(prefix)
		out.String(string(*in.ClientID))
	}
	if in.ClientEmail != nil {
		const prefix string = ",\"client_email\":"
		out.RawString(prefix)
		out.String(string(*in.ClientEmail))
	}
	if in.ClientAvatar != nil {
		const prefix string = ",\"client_avatar\":"
		out.RawString(prefix)
		out.String(string(*in.ClientAvatar))
	}
	if in.ServiceID != nil {
		const prefix string = ",\"service_id\":"
		out.RawString(prefix)
		out.String(string(*in.ServiceID))
	}
	if in.ServiceTitle != nil {
		const prefix string = ",\"service_title\":"
		out.RawString(prefix)
		out.String(string(*in.ServiceTitle))
	}
	if in.Price != nil {
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Float64(float64(*in.Price))
	}
	if in.Duration != nil {
		const prefix string = ",\"duration_minutes\":"
		out.RawString(prefix)
		out.Int(int(*in.Duration))
	}
	{
		const prefix string = ",\"start_at\":"
		out.RawString(prefix)
		out.Raw((in.StartAt).MarshalJSON())
	}
	{
		const prefix string = ",\"end_at\":"
		out.RawString(prefix)
		out.Raw((in.EndAt).MarshalJSON())
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"is_manual_block\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsManualBlock))
	}
	if in.ClientComment != nil {
		const prefix string = ",\"client_comment\":"
		out.RawString(prefix)
		out.String(string(*in.ClientComment))
	}
	if in.MasterNote != nil {
		const prefix string = ",\"master_note\":"
		out.RawString(prefix)
		out.String(string(*in.MasterNote))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MasterAppointmentView) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF3eb2881EncodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MasterAppointmentView) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF3eb2881EncodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MasterAppointmentView) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF3eb2881DecodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MasterAppointmentView) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF3eb2881DecodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto1(l, v)
}
func easyjsonF3eb2881DecodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto2(in *jlexer.Lexer, out *CreateManualBlockResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "start_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.StartAt).UnmarshalJSON(data))
				}
			}
		case "end_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.EndAt).UnmarshalJSON(data))
				}
			}
		case "note":
			if in.IsNull() {
				in.Skip()
				out.Note = nil
			} else {
				if out.Note == nil {
					out.Note = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Note = string(in.String())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF3eb2881EncodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto2(out *jwriter.Writer, in CreateManualBlockResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"start_at\":"
		out.RawString(prefix)
		out.Raw((in.StartAt).MarshalJSON())
	}
	{
		const prefix string = ",\"end_at\":"
		out.RawString(prefix)
		out.Raw((in.EndAt).MarshalJSON())
	}
	if in.Note != nil {
		const prefix string = ",\"note\":"
		out.RawString(prefix)
		out.String(string(*in.Note))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateManualBlockResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF3eb2881EncodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateManualBlockResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF3eb2881EncodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateManualBlockResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF3eb2881DecodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateManualBlockResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF3eb2881DecodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto2(l, v)
}
func easyjsonF3eb2881DecodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto3(in *jlexer.Lexer, out *CreateManualBlockRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "start_at":
			if in.IsNull() {
				in.Skip()
			} else {
				out.StartAt = string(in.String())
			}
		case "end_at":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EndAt = string(in.String())
			}
		case "note":
			if in.IsNull() {
				in.Skip()
				out.Note = nil
			} else {
				if out.Note == nil {
					out.Note = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Note = string(in.String())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF3eb2881EncodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto3(out *jwriter.Writer, in CreateManualBlockRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"start_at\":"
		out.RawString(prefix[1:])
		out.String(string(in.StartAt))
	}
	{
		const prefix string = ",\"end_at\":"
		out.RawString(prefix)
		out.String(string(in.EndAt))
	}
	if in.Note != nil {
		const prefix string = ",\"note\":"
		out.RawString(prefix)
		out.String(string(*in.Note))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateManualBlockRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF3eb2881EncodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateManualBlockRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF3eb2881EncodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateManualBlockRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF3eb2881DecodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateManualBlockRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF3eb2881DecodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto3(l, v)
}
func easyjsonF3eb2881DecodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto4(in *jlexer.Lexer, out *ClientAppointmentView) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "master_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MasterID = string(in.String())
			}
		case "master_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MasterName = string(in.String())
			}
		case "master_avatar":
			if in.IsNull() {
				in.Skip()
				out.MasterAvatar = nil
			} else {
				if out.MasterAvatar == nil {
					out.MasterAvatar = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.MasterAvatar = string(in.String())
				}
			}
		case "master_lat":
			if in.IsNull() {
				in.Skip()
				out.MasterLat = nil
			} else {
				if out.MasterLat == nil {
					out.MasterLat = new(float64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.MasterLat = float64(in.Float64())
				}
			}
		case "master_lon":
			if in.IsNull() {
				in.Skip()
				out.MasterLon = nil
			} else {
				if out.MasterLon == nil {
					out.MasterLon = new(float64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.MasterLon = float64(in.Float64())
				}
			}
		case "service_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ServiceID = string(in.String())
			}
		case "service_title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ServiceTitle = string(in.String())
			}
		case "price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Price = float64(in.Float64())
			}
		case "duration_minutes":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Duration = int(in.Int())
			}
		case "start_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.StartAt).UnmarshalJSON(data))
				}
			}
		case "end_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.EndAt).UnmarshalJSON(data))
				}
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "client_comment":
			if in.IsNull() {
				in.Skip()
				out.ClientComment = nil
			} else {
				if out.ClientComment == nil {
					out.ClientComment = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.ClientComment = string(in.String())
				}
			}
		case "master_note":
			if in.IsNull() {
				in.Skip()
				out.MasterNote = nil
			} else {
				if out.MasterNote == nil {
					out.MasterNote = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.MasterNote = string(in.String())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF3eb2881EncodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto4(out *jwriter.Writer, in ClientAppointmentView) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"master_id\":"
		out.RawString(prefix)
		out.String(string(in.MasterID))
	}
	{
		const prefix string = ",\"master_name\":"
		out.RawString(prefix)
		out.String(string(in.MasterName))
	}
	if in.MasterAvatar != nil {
		const prefix string = ",\"master_avatar\":"
		out.RawString(prefix)
		out.String(string(*in.MasterAvatar))
	}
	if in.MasterLat != nil {
		const prefix string = ",\"master_lat\":"
		out.RawString(prefix)
		out.Float64(float64(*in.MasterLat))
	}
	if in.MasterLon != nil {
		const prefix string = ",\"master_lon\":"
		out.RawString(prefix)
		out.Float64(float64(*in.MasterLon))
	}
	{
		const prefix string = ",\"service_id\":"
		out.RawString(prefix)
		out.String(string(in.ServiceID))
	}
	{
		const prefix string = ",\"service_title\":"
		out.RawString(prefix)
		out.String(string(in.ServiceTitle))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Float64(float64(in.Price))
	}
	{
		const prefix string = ",\"duration_minutes\":"
		out.RawString(prefix)
		out.Int(int(in.Duration))
	}
	{
		const prefix string = ",\"start_at\":"
		out.RawString(prefix)
		out.Raw((in.StartAt).MarshalJSON())
	}
	{
		const prefix string = ",\"end_at\":"
		out.RawString(prefix)
		out.Raw((in.EndAt).MarshalJSON())
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	if in.ClientComment != nil {
		const prefix string = ",\"client_comment\":"
		out.RawString(prefix)
		out.String(string(*in.ClientComment))
	}
	if in.MasterNote != nil {
		const prefix string = ",\"master_note\":"
		out.RawString(prefix)
		out.String(string(*in.MasterNote))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ClientAppointmentView) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF3eb2881EncodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ClientAppointmentView) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF3eb2881EncodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ClientAppointmentView) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF3eb2881DecodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ClientAppointmentView) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF3eb2881DecodeGithubComRBSTeamOkoshkiMicroservicesCoreBookingDto4(l, v)
}
