// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonB30beec6DecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto(in *jlexer.Lexer, out *UpdateMasterRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
				out.Name = nil
			} else {
				if out.Name == nil {
					out.Name = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Name = string(in.String())
				}
			}
		case "bio":
			if in.IsNull() {
				in.Skip()
				out.Bio = nil
			} else {
				if out.Bio == nil {
					out.Bio = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Bio = string(in.String())
				}
			}
		case "timezone":
			if in.IsNull() {
				in.Skip()
				out.Timezone = nil
			} else {
				if out.Timezone == nil {
					out.Timezone = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Timezone = string(in.String())
				}
			}
		case "lat":
			if in.IsNull() {
				in.Skip()
				out.Lat = nil
			} else {
				if out.Lat == nil {
					out.Lat = new(float64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Lat = float64(in.Float64())
				}
			}
		case "lon":
			if in.IsNull() {
				in.Skip()
				out.Lon = nil
			} else {
				if out.Lon == nil {
					out.Lon = new(float64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Lon = float64(in.Float64())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB30beec6EncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto(out *jwriter.Writer, in UpdateMasterRequest) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Name != nil {
		const prefix string = ",\"name\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(*in.Name))
	}
	if in.Bio != nil {
		const prefix string = ",\"bio\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.Bio))
	}
	if in.Timezone != nil {
		const prefix string = ",\"timezone\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.Timezone))
	}
	if in.Lat != nil {
		const prefix string = ",\"lat\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float64(float64(*in.Lat))
	}
	if in.Lon != nil {
		const prefix string = ",\"lon\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float64(float64(*in.Lon))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UpdateMasterRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB30beec6EncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UpdateMasterRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB30beec6EncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UpdateMasterRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB30beec6DecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UpdateMasterRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB30beec6DecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto(l, v)
}
func easyjsonB30beec6DecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto1(in *jlexer.Lexer, out *Master) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = string(in.String())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "bio":
			if in.IsNull() {
				in.Skip()
				out.Bio = nil
			} else {
				if out.Bio == nil {
					out.Bio = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Bio = string(in.String())
				}
			}
		case "avatar_url":
			if in.IsNull() {
				in.Skip()
				out.AvatarURL = nil
			} else {
				if out.AvatarURL == nil {
					out.AvatarURL = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.AvatarURL = string(in.String())
				}
			}
		case "timezone":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Timezone = string(in.String())
			}
		case "lat":
			if in.IsNull() {
				in.Skip()
				out.Lat = nil
			} else {
				if out.Lat == nil {
					out.Lat = new(float64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Lat = float64(in.Float64())
				}
			}
		case "lon":
			if in.IsNull() {
				in.Skip()
				out.Lon = nil
			} else {
				if out.Lon == nil {
					out.Lon = new(float64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Lon = float64(in.Float64())
				}
			}
		case "rating":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Rating = float64(in.Float64())
			}
		case "review_count":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ReviewCount = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB30beec6EncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto1(out *jwriter.Writer, in Master) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix)
		out.String(string(in.UserID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	if in.Bio != nil {
		const prefix string = ",\"bio\":"
		out.RawString(prefix)
		out.String(string(*in.Bio))
	}
	if in.AvatarURL != nil {
		const prefix string = ",\"avatar_url\":"
		out.RawString(prefix)
		out.String(string(*in.AvatarURL))
	}
	{
		const prefix string = ",\"timezone\":"
		out.RawString(prefix)
		out.String(string(in.Timezone))
	}
	if in.Lat != nil {
		const prefix string = ",\"lat\":"
		out.RawString(prefix)
		out.Float64(float64(*in.Lat))
	}
	if in.Lon != nil {
		const prefix string = ",\"lon\":"
		out.RawString(prefix)
		out.Float64(float64(*in.Lon))
	}
	{
		const prefix string = ",\"rating\":"
		out.RawString(prefix)
		out.Float64(float64(in.Rating))
	}
	{
		const prefix string = ",\"review_count\":"
		out.RawString(prefix)
		out.Int(int(in.ReviewCount))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Master) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB30beec6EncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Master) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB30beec6EncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Master) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB30beec6DecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Master) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB30beec6DecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto1(l, v)
}
func easyjsonB30beec6DecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto2(in *jlexer.Lexer, out *CreateMasterRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "bio":
			if in.IsNull() {
				in.Skip()
				out.Bio = nil
			} else {
				if out.Bio == nil {
					out.Bio = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Bio = string(in.String())
				}
			}
		case "timezone":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Timezone = string(in.String())
			}
		case "lat":
			if in.IsNull() {
				in.Skip()
				out.Lat = nil
			} else {
				if out.Lat == nil {
					out.Lat = new(float64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Lat = float64(in.Float64())
				}
			}
		case "lon":
			if in.IsNull() {
				in.Skip()
				out.Lon = nil
			} else {
				if out.Lon == nil {
					out.Lon = new(float64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Lon = float64(in.Float64())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB30beec6EncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto2(out *jwriter.Writer, in CreateMasterRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	if in.Bio != nil {
		const prefix string = ",\"bio\":"
		out.RawString(prefix)
		out.String(string(*in.Bio))
	}
	if in.Timezone != "" {
		const prefix string = ",\"timezone\":"
		out.RawString(prefix)
		out.String(string(in.Timezone))
	}
	if in.Lat != nil {
		const prefix string = ",\"lat\":"
		out.RawString(prefix)
		out.Float64(float64(*in.Lat))
	}
	if in.Lon != nil {
		const prefix string = ",\"lon\":"
		out.RawString(prefix)
		out.Float64(float64(*in.Lon))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateMasterRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB30beec6EncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateMasterRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB30beec6EncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateMasterRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB30beec6DecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateMasterRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB30beec6DecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto2(l, v)
}
