// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonFe2a3464DecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto(in *jlexer.Lexer, out *UpsertMasterSettingsRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "slot_step_minutes":
			if in.IsNull() {
				in.Skip()
				out.SlotStepMinutes = nil
			} else {
				if out.SlotStepMinutes == nil {
					out.SlotStepMinutes = new(int)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.SlotStepMinutes = int(in.Int())
				}
			}
		case "lead_time_minutes":
			if in.IsNull() {
				in.Skip()
				out.LeadTimeMinutes = nil
			} else {
				if out.LeadTimeMinutes == nil {
					out.LeadTimeMinutes = new(int)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.LeadTimeMinutes = int(in.Int())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFe2a3464EncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto(out *jwriter.Writer, in UpsertMasterSettingsRequest) {
	out.RawByte('{')
	first := true
	_ = first
	if in.SlotStepMinutes != nil {
		const prefix string = ",\"slot_step_minutes\":"
		first = false
		out.RawString(prefix[1:])
		out.Int(int(*in.SlotStepMinutes))
	}
	if in.LeadTimeMinutes != nil {
		const prefix string = ",\"lead_time_minutes\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(*in.LeadTimeMinutes))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UpsertMasterSettingsRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFe2a3464EncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UpsertMasterSettingsRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFe2a3464EncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UpsertMasterSettingsRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFe2a3464DecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UpsertMasterSettingsRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFe2a3464DecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto(l, v)
}
func easyjsonFe2a3464DecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto1(in *jlexer.Lexer, out *MasterSettings) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "master_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MasterID = string(in.String())
			}
		case "slot_step_minutes":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SlotStepMinutes = int(in.Int())
			}
		case "lead_time_minutes":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LeadTimeMinutes = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFe2a3464EncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto1(out *jwriter.Writer, in MasterSettings) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"master_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.MasterID))
	}
	{
		const prefix string = ",\"slot_step_minutes\":"
		out.RawString(prefix)
		out.Int(int(in.SlotStepMinutes))
	}
	{
		const prefix string = ",\"lead_time_minutes\":"
		out.RawString(prefix)
		out.Int(int(in.LeadTimeMinutes))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MasterSettings) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFe2a3464EncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MasterSettings) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFe2a3464EncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MasterSettings) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFe2a3464DecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MasterSettings) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFe2a3464DecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto1(l, v)
}
