// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonA7c3c05fDecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto(in *jlexer.Lexer, out *WorkingHoursDayRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "day_of_week":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DayOfWeek = int(in.Int())
			}
		case "start_time":
			if in.IsNull() {
				in.Skip()
				out.StartTime = nil
			} else {
				if out.StartTime == nil {
					out.StartTime = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.StartTime = string(in.String())
				}
			}
		case "end_time":
			if in.IsNull() {
				in.Skip()
				out.EndTime = nil
			} else {
				if out.EndTime == nil {
					out.EndTime = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.EndTime = string(in.String())
				}
			}
		case "is_day_off":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsDayOff = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA7c3c05fEncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto(out *jwriter.Writer, in WorkingHoursDayRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"day_of_week\":"
		out.RawString(prefix[1:])
		out.Int(int(in.DayOfWeek))
	}
	if in.StartTime != nil {
		const prefix string = ",\"start_time\":"
		out.RawString(prefix)
		out.String(string(*in.StartTime))
	}
	if in.EndTime != nil {
		const prefix string = ",\"end_time\":"
		out.RawString(prefix)
		out.String(string(*in.EndTime))
	}
	{
		const prefix string = ",\"is_day_off\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsDayOff))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v WorkingHoursDayRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonA7c3c05fEncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WorkingHoursDayRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA7c3c05fEncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WorkingHoursDayRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonA7c3c05fDecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WorkingHoursDayRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA7c3c05fDecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto(l, v)
}
func easyjsonA7c3c05fDecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto1(in *jlexer.Lexer, out *WorkingHours) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "master_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MasterID = string(in.String())
			}
		case "day_of_week":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DayOfWeek = int(in.Int())
			}
		case "start_time":
			if in.IsNull() {
				in.Skip()
				out.StartTime = nil
			} else {
				if out.StartTime == nil {
					out.StartTime = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.StartTime = string(in.String())
				}
			}
		case "end_time":
			if in.IsNull() {
				in.Skip()
				out.EndTime = nil
			} else {
				if out.EndTime == nil {
					out.EndTime = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.EndTime = string(in.String())
				}
			}
		case "is_day_off":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsDayOff = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA7c3c05fEncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto1(out *jwriter.Writer, in WorkingHours) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"master_id\":"
		out.RawString(prefix)
		out.String(string(in.MasterID))
	}
	{
		const prefix string = ",\"day_of_week\":"
		out.RawString(prefix)
		out.Int(int(in.DayOfWeek))
	}
	if in.StartTime != nil {
		const prefix string = ",\"start_time\":"
		out.RawString(prefix)
		out.String(string(*in.StartTime))
	}
	if in.EndTime != nil {
		const prefix string = ",\"end_time\":"
		out.RawString(prefix)
		out.String(string(*in.EndTime))
	}
	{
		const prefix string = ",\"is_day_off\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsDayOff))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v WorkingHours) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonA7c3c05fEncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WorkingHours) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA7c3c05fEncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WorkingHours) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonA7c3c05fDecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WorkingHours) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA7c3c05fDecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto1(l, v)
}
func easyjsonA7c3c05fDecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto2(in *jlexer.Lexer, out *UpdateWorkingHoursBulkRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "days":
			if in.IsNull() {
				in.Skip()
				out.Days = nil
			} else {
				in.Delim('[')
				if out.Days == nil {
					if !in.IsDelim(']') {
						out.Days = make([]WorkingHoursDayRequest, 0, 2)
					} else {
						out.Days = []WorkingHoursDayRequest{}
					}
				} else {
					out.Days = (out.Days)[:0]
				}
				for !in.IsDelim(']') {
					var v1 WorkingHoursDayRequest
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Days = append(out.Days, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA7c3c05fEncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto2(out *jwriter.Writer, in UpdateWorkingHoursBulkRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"days\":"
		out.RawString(prefix[1:])
		if in.Days == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Days {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UpdateWorkingHoursBulkRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonA7c3c05fEncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UpdateWorkingHoursBulkRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA7c3c05fEncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UpdateWorkingHoursBulkRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonA7c3c05fDecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UpdateWorkingHoursBulkRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA7c3c05fDecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto2(l, v)
}
func easyjsonA7c3c05fDecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto3(in *jlexer.Lexer, out *UpdateScheduleExceptionRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "start_time":
			if in.IsNull() {
				in.Skip()
				out.StartTime = nil
			} else {
				if out.StartTime == nil {
					out.StartTime = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.StartTime = string(in.String())
				}
			}
		case "end_time":
			if in.IsNull() {
				in.Skip()
				out.EndTime = nil
			} else {
				if out.EndTime == nil {
					out.EndTime = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.EndTime = string(in.String())
				}
			}
		case "is_working":
			if in.IsNull() {
				in.Skip()
				out.IsWorking = nil
			} else {
				if out.IsWorking == nil {
					out.IsWorking = new(bool)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.IsWorking = bool(in.Bool())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA7c3c05fEncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto3(out *jwriter.Writer, in UpdateScheduleExceptionRequest) {
	out.RawByte('{')
	first := true
	_ = first
	if in.StartTime != nil {
		const prefix string = ",\"start_time\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(*in.StartTime))
	}
	if in.EndTime != nil {
		const prefix string = ",\"end_time\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.EndTime))
	}
	if in.IsWorking != nil {
		const prefix string = ",\"is_working\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(*in.IsWorking))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UpdateScheduleExceptionRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonA7c3c05fEncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UpdateScheduleExceptionRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA7c3c05fEncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UpdateScheduleExceptionRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonA7c3c05fDecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UpdateScheduleExceptionRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA7c3c05fDecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto3(l, v)
}
func easyjsonA7c3c05fDecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto4(in *jlexer.Lexer, out *ScheduleException) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "master_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MasterID = string(in.String())
			}
		case "exception_date":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ExceptionDate = string(in.String())
			}
		case "start_time":
			if in.IsNull() {
				in.Skip()
				out.StartTime = nil
			} else {
				if out.StartTime == nil {
					out.StartTime = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.StartTime = string(in.String())
				}
			}
		case "end_time":
			if in.IsNull() {
				in.Skip()
				out.EndTime = nil
			} else {
				if out.EndTime == nil {
					out.EndTime = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.EndTime = string(in.String())
				}
			}
		case "is_working":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsWorking = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA7c3c05fEncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto4(out *jwriter.Writer, in ScheduleException) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"master_id\":"
		out.RawString(prefix)
		out.String(string(in.MasterID))
	}
	{
		const prefix string = ",\"exception_date\":"
		out.RawString(prefix)
		out.String(string(in.ExceptionDate))
	}
	if in.StartTime != nil {
		const prefix string = ",\"start_time\":"
		out.RawString(prefix)
		out.String(string(*in.StartTime))
	}
	if in.EndTime != nil {
		const prefix string = ",\"end_time\":"
		out.RawString(prefix)
		out.String(string(*in.EndTime))
	}
	{
		const prefix string = ",\"is_working\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsWorking))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ScheduleException) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonA7c3c05fEncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ScheduleException) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA7c3c05fEncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ScheduleException) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonA7c3c05fDecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ScheduleException) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA7c3c05fDecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto4(l, v)
}
func easyjsonA7c3c05fDecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto5(in *jlexer.Lexer, out *CreateScheduleExceptionRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "exception_date":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ExceptionDate = string(in.String())
			}
		case "start_time":
			if in.IsNull() {
				in.Skip()
				out.StartTime = nil
			} else {
				if out.StartTime == nil {
					out.StartTime = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.StartTime = string(in.String())
				}
			}
		case "end_time":
			if in.IsNull() {
				in.Skip()
				out.EndTime = nil
			} else {
				if out.EndTime == nil {
					out.EndTime = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.EndTime = string(in.String())
				}
			}
		case "is_working":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsWorking = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA7c3c05fEncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto5(out *jwriter.Writer, in CreateScheduleExceptionRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"exception_date\":"
		out.RawString(prefix[1:])
		out.String(string(in.ExceptionDate))
	}
	if in.StartTime != nil {
		const prefix string = ",\"start_time\":"
		out.RawString(prefix)
		out.String(string(*in.StartTime))
	}
	if in.EndTime != nil {
		const prefix string = ",\"end_time\":"
		out.RawString(prefix)
		out.String(string(*in.EndTime))
	}
	{
		const prefix string = ",\"is_working\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsWorking))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateScheduleExceptionRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonA7c3c05fEncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateScheduleExceptionRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA7c3c05fEncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateScheduleExceptionRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonA7c3c05fDecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateScheduleExceptionRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA7c3c05fDecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto5(l, v)
}
