// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson1717d861DecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto(in *jlexer.Lexer, out *ServiceWithMaster) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "category_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CategoryID = string(in.String())
			}
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		case "city":
			if in.IsNull() {
				in.Skip()
			} else {
				out.City = string(in.String())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
				out.Description = nil
			} else {
				if out.Description == nil {
					out.Description = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Description = string(in.String())
				}
			}
		case "price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Price = int64(in.Int64())
			}
		case "duration_minutes":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DurationMinutes = int(in.Int())
			}
		case "lat":
			if in.IsNull() {
				in.Skip()
				out.Lat = nil
			} else {
				if out.Lat == nil {
					out.Lat = new(float64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Lat = float64(in.Float64())
				}
			}
		case "lon":
			if in.IsNull() {
				in.Skip()
				out.Lon = nil
			} else {
				if out.Lon == nil {
					out.Lon = new(float64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Lon = float64(in.Float64())
				}
			}
		case "is_active":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsActive = bool(in.Bool())
			}
		case "is_auto_confirm":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsAutoConfirm = bool(in.Bool())
			}
		case "master_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MasterID = string(in.String())
			}
		case "first_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FirstName = string(in.String())
			}
		case "last_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastName = string(in.String())
			}
		case "phone":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Phone = string(in.String())
			}
		case "master_address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MasterAddress = string(in.String())
			}
		case "master_city":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MasterCity = string(in.String())
			}
		case "bio":
			if in.IsNull() {
				in.Skip()
				out.Bio = nil
			} else {
				if out.Bio == nil {
					out.Bio = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Bio = string(in.String())
				}
			}
		case "avatar_url":
			if in.IsNull() {
				in.Skip()
				out.AvatarURL = nil
			} else {
				if out.AvatarURL == nil {
					out.AvatarURL = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.AvatarURL = string(in.String())
				}
			}
		case "timezone":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Timezone = string(in.String())
			}
		case "master_lat":
			if in.IsNull() {
				in.Skip()
				out.MasterLat = nil
			} else {
				if out.MasterLat == nil {
					out.MasterLat = new(float64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.MasterLat = float64(in.Float64())
				}
			}
		case "master_lon":
			if in.IsNull() {
				in.Skip()
				out.MasterLon = nil
			} else {
				if out.MasterLon == nil {
					out.MasterLon = new(float64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.MasterLon = float64(in.Float64())
				}
			}
		case "rating":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Rating = float64(in.Float64())
			}
		case "review_count":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ReviewCount = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1717d861EncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto(out *jwriter.Writer, in ServiceWithMaster) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"category_id\":"
		out.RawString(prefix)
		out.String(string(in.CategoryID))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"city\":"
		out.RawString(prefix)
		out.String(string(in.City))
	}
	if in.Description != nil {
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(*in.Description))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Int64(int64(in.Price))
	}
	{
		const prefix string = ",\"duration_minutes\":"
		out.RawString(prefix)
		out.Int(int(in.DurationMinutes))
	}
	if in.Lat != nil {
		const prefix string = ",\"lat\":"
		out.RawString(prefix)
		out.Float64(float64(*in.Lat))
	}
	if in.Lon != nil {
		const prefix string = ",\"lon\":"
		out.RawString(prefix)
		out.Float64(float64(*in.Lon))
	}
	{
		const prefix string = ",\"is_active\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsActive))
	}
	{
		const prefix string = ",\"is_auto_confirm\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsAutoConfirm))
	}
	{
		const prefix string = ",\"master_id\":"
		out.RawString(prefix)
		out.String(string(in.MasterID))
	}
	{
		const prefix string = ",\"first_name\":"
		out.RawString(prefix)
		out.String(string(in.FirstName))
	}
	{
		const prefix string = ",\"last_name\":"
		out.RawString(prefix)
		out.String(string(in.LastName))
	}
	{
		const prefix string = ",\"phone\":"
		out.RawString(prefix)
		out.String(string(in.Phone))
	}
	{
		const prefix string = ",\"master_address\":"
		out.RawString(prefix)
		out.String(string(in.MasterAddress))
	}
	{
		const prefix string = ",\"master_city\":"
		out.RawString(prefix)
		out.String(string(in.MasterCity))
	}
	if in.Bio != nil {
		const prefix string = ",\"bio\":"
		out.RawString(prefix)
		out.String(string(*in.Bio))
	}
	if in.AvatarURL != nil {
		const prefix string = ",\"avatar_url\":"
		out.RawString(prefix)
		out.String(string(*in.AvatarURL))
	}
	{
		const prefix string = ",\"timezone\":"
		out.RawString(prefix)
		out.String(string(in.Timezone))
	}
	if in.MasterLat != nil {
		const prefix string = ",\"master_lat\":"
		out.RawString(prefix)
		out.Float64(float64(*in.MasterLat))
	}
	if in.MasterLon != nil {
		const prefix string = ",\"master_lon\":"
		out.RawString(prefix)
		out.Float64(float64(*in.MasterLon))
	}
	{
		const prefix string = ",\"rating\":"
		out.RawString(prefix)
		out.Float64(float64(in.Rating))
	}
	{
		const prefix string = ",\"review_count\":"
		out.RawString(prefix)
		out.Int(int(in.ReviewCount))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ServiceWithMaster) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1717d861EncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ServiceWithMaster) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1717d861EncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ServiceWithMaster) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1717d861DecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ServiceWithMaster) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1717d861DecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto(l, v)
}
func easyjson1717d861DecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto1(in *jlexer.Lexer, out *ServiceItem) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "master_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MasterID = string(in.String())
			}
		case "category_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CategoryID = string(in.String())
			}
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		case "city":
			if in.IsNull() {
				in.Skip()
			} else {
				out.City = string(in.String())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
				out.Description = nil
			} else {
				if out.Description == nil {
					out.Description = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Description = string(in.String())
				}
			}
		case "price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Price = int64(in.Int64())
			}
		case "duration_minutes":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DurationMinutes = int(in.Int())
			}
		case "lat":
			if in.IsNull() {
				in.Skip()
				out.Lat = nil
			} else {
				if out.Lat == nil {
					out.Lat = new(float64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Lat = float64(in.Float64())
				}
			}
		case "lon":
			if in.IsNull() {
				in.Skip()
				out.Lon = nil
			} else {
				if out.Lon == nil {
					out.Lon = new(float64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Lon = float64(in.Float64())
				}
			}
		case "is_active":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsActive = bool(in.Bool())
			}
		case "is_auto_confirm":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsAutoConfirm = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1717d861EncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto1(out *jwriter.Writer, in ServiceItem) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"master_id\":"
		out.RawString(prefix)
		out.String(string(in.MasterID))
	}
	{
		const prefix string = ",\"category_id\":"
		out.RawString(prefix)
		out.String(string(in.CategoryID))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"city\":"
		out.RawString(prefix)
		out.String(string(in.City))
	}
	if in.Description != nil {
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(*in.Description))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Int64(int64(in.Price))
	}
	{
		const prefix string = ",\"duration_minutes\":"
		out.RawString(prefix)
		out.Int(int(in.DurationMinutes))
	}
	if in.Lat != nil {
		const prefix string = ",\"lat\":"
		out.RawString(prefix)
		out.Float64(float64(*in.Lat))
	}
	if in.Lon != nil {
		const prefix string = ",\"lon\":"
		out.RawString(prefix)
		out.Float64(float64(*in.Lon))
	}
	{
		const prefix string = ",\"is_active\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsActive))
	}
	{
		const prefix string = ",\"is_auto_confirm\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsAutoConfirm))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ServiceItem) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1717d861EncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ServiceItem) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1717d861EncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ServiceItem) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1717d861DecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ServiceItem) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1717d861DecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto1(l, v)
}
func easyjson1717d861DecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto2(in *jlexer.Lexer, out *CreateServiceItemRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "category_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CategoryID = string(in.String())
			}
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		case "city":
			if in.IsNull() {
				in.Skip()
			} else {
				out.City = string(in.String())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
				out.Description = nil
			} else {
				if out.Description == nil {
					out.Description = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Description = string(in.String())
				}
			}
		case "price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Price = int64(in.Int64())
			}
		case "duration_minutes":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DurationMinutes = int(in.Int())
			}
		case "lat":
			if in.IsNull() {
				in.Skip()
				out.Lat = nil
			} else {
				if out.Lat == nil {
					out.Lat = new(float64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Lat = float64(in.Float64())
				}
			}
		case "lon":
			if in.IsNull() {
				in.Skip()
				out.Lon = nil
			} else {
				if out.Lon == nil {
					out.Lon = new(float64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Lon = float64(in.Float64())
				}
			}
		case "is_auto_confirm":
			if in.IsNull() {
				in.Skip()
				out.IsAutoConfirm = nil
			} else {
				if out.IsAutoConfirm == nil {
					out.IsAutoConfirm = new(bool)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.IsAutoConfirm = bool(in.Bool())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1717d861EncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto2(out *jwriter.Writer, in CreateServiceItemRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"category_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.CategoryID))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"city\":"
		out.RawString(prefix)
		out.String(string(in.City))
	}
	if in.Description != nil {
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(*in.Description))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Int64(int64(in.Price))
	}
	{
		const prefix string = ",\"duration_minutes\":"
		out.RawString(prefix)
		out.Int(int(in.DurationMinutes))
	}
	if in.Lat != nil {
		const prefix string = ",\"lat\":"
		out.RawString(prefix)
		out.Float64(float64(*in.Lat))
	}
	if in.Lon != nil {
		const prefix string = ",\"lon\":"
		out.RawString(prefix)
		out.Float64(float64(*in.Lon))
	}
	if in.IsAutoConfirm != nil {
		const prefix string = ",\"is_auto_confirm\":"
		out.RawString(prefix)
		out.Bool(bool(*in.IsAutoConfirm))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateServiceItemRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1717d861EncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateServiceItemRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1717d861EncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateServiceItemRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1717d861DecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateServiceItemRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1717d861DecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto2(l, v)
}
