// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson1717d861DecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto(in *jlexer.Lexer, out *ServiceWithMaster) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "category_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CategoryID = string(in.String())
			}
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
				out.Description = nil
			} else {
				if out.Description == nil {
					out.Description = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Description = string(in.String())
				}
			}
		case "price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Price = float64(in.Float64())
			}
		case "duration_minutes":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DurationMinutes = int(in.Int())
			}
		case "buffer_before_minutes":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BufferBeforeMinutes = int(in.Int())
			}
		case "buffer_after_minutes":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BufferAfterMinutes = int(in.Int())
			}
		case "is_active":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsActive = bool(in.Bool())
			}
		case "master":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Master).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1717d861EncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto(out *jwriter.Writer, in ServiceWithMaster) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"category_id\":"
		out.RawString(prefix)
		out.String(string(in.CategoryID))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	if in.Description != nil {
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(*in.Description))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Float64(float64(in.Price))
	}
	{
		const prefix string = ",\"duration_minutes\":"
		out.RawString(prefix)
		out.Int(int(in.DurationMinutes))
	}
	{
		const prefix string = ",\"buffer_before_minutes\":"
		out.RawString(prefix)
		out.Int(int(in.BufferBeforeMinutes))
	}
	{
		const prefix string = ",\"buffer_after_minutes\":"
		out.RawString(prefix)
		out.Int(int(in.BufferAfterMinutes))
	}
	{
		const prefix string = ",\"is_active\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsActive))
	}
	{
		const prefix string = ",\"master\":"
		out.RawString(prefix)
		(in.Master).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ServiceWithMaster) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1717d861EncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ServiceWithMaster) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1717d861EncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ServiceWithMaster) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1717d861DecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ServiceWithMaster) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1717d861DecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto(l, v)
}
func easyjson1717d861DecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto1(in *jlexer.Lexer, out *ServiceItem) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "master_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MasterID = string(in.String())
			}
		case "category_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CategoryID = string(in.String())
			}
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
				out.Description = nil
			} else {
				if out.Description == nil {
					out.Description = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Description = string(in.String())
				}
			}
		case "price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Price = float64(in.Float64())
			}
		case "duration_minutes":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DurationMinutes = int(in.Int())
			}
		case "buffer_before_minutes":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BufferBeforeMinutes = int(in.Int())
			}
		case "buffer_after_minutes":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BufferAfterMinutes = int(in.Int())
			}
		case "is_active":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsActive = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1717d861EncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto1(out *jwriter.Writer, in ServiceItem) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"master_id\":"
		out.RawString(prefix)
		out.String(string(in.MasterID))
	}
	{
		const prefix string = ",\"category_id\":"
		out.RawString(prefix)
		out.String(string(in.CategoryID))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	if in.Description != nil {
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(*in.Description))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Float64(float64(in.Price))
	}
	{
		const prefix string = ",\"duration_minutes\":"
		out.RawString(prefix)
		out.Int(int(in.DurationMinutes))
	}
	{
		const prefix string = ",\"buffer_before_minutes\":"
		out.RawString(prefix)
		out.Int(int(in.BufferBeforeMinutes))
	}
	{
		const prefix string = ",\"buffer_after_minutes\":"
		out.RawString(prefix)
		out.Int(int(in.BufferAfterMinutes))
	}
	{
		const prefix string = ",\"is_active\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsActive))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ServiceItem) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1717d861EncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ServiceItem) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1717d861EncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ServiceItem) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1717d861DecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ServiceItem) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1717d861DecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto1(l, v)
}
func easyjson1717d861DecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto2(in *jlexer.Lexer, out *CreateServiceItemRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "category_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CategoryID = string(in.String())
			}
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
				out.Description = nil
			} else {
				if out.Description == nil {
					out.Description = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Description = string(in.String())
				}
			}
		case "price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Price = float64(in.Float64())
			}
		case "duration_minutes":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DurationMinutes = int(in.Int())
			}
		case "buffer_before_minutes":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BufferBeforeMinutes = int(in.Int())
			}
		case "buffer_after_minutes":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BufferAfterMinutes = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1717d861EncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto2(out *jwriter.Writer, in CreateServiceItemRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"category_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.CategoryID))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	if in.Description != nil {
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(*in.Description))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Float64(float64(in.Price))
	}
	{
		const prefix string = ",\"duration_minutes\":"
		out.RawString(prefix)
		out.Int(int(in.DurationMinutes))
	}
	if in.BufferBeforeMinutes != 0 {
		const prefix string = ",\"buffer_before_minutes\":"
		out.RawString(prefix)
		out.Int(int(in.BufferBeforeMinutes))
	}
	if in.BufferAfterMinutes != 0 {
		const prefix string = ",\"buffer_after_minutes\":"
		out.RawString(prefix)
		out.Int(int(in.BufferAfterMinutes))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateServiceItemRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1717d861EncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateServiceItemRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1717d861EncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateServiceItemRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1717d861DecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateServiceItemRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1717d861DecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto2(l, v)
}
