// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson1c21b86fDecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto(in *jlexer.Lexer, out *WorkIntervalList) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "intervals":
			if in.IsNull() {
				in.Skip()
				out.Intervals = nil
			} else {
				in.Delim('[')
				if out.Intervals == nil {
					if !in.IsDelim(']') {
						out.Intervals = make([]WorkInterval, 0, 0)
					} else {
						out.Intervals = []WorkInterval{}
					}
				} else {
					out.Intervals = (out.Intervals)[:0]
				}
				for !in.IsDelim(']') {
					var v1 WorkInterval
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Intervals = append(out.Intervals, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1c21b86fEncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto(out *jwriter.Writer, in WorkIntervalList) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"intervals\":"
		out.RawString(prefix[1:])
		if in.Intervals == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Intervals {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v WorkIntervalList) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1c21b86fEncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WorkIntervalList) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1c21b86fEncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WorkIntervalList) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1c21b86fDecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WorkIntervalList) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1c21b86fDecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto(l, v)
}
func easyjson1c21b86fDecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto1(in *jlexer.Lexer, out *WorkInterval) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "master_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MasterID = string(in.String())
			}
		case "date":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Date = string(in.String())
			}
		case "start_time":
			if in.IsNull() {
				in.Skip()
			} else {
				out.StartTime = string(in.String())
			}
		case "end_time":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EndTime = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1c21b86fEncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto1(out *jwriter.Writer, in WorkInterval) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"master_id\":"
		out.RawString(prefix)
		out.String(string(in.MasterID))
	}
	{
		const prefix string = ",\"date\":"
		out.RawString(prefix)
		out.String(string(in.Date))
	}
	{
		const prefix string = ",\"start_time\":"
		out.RawString(prefix)
		out.String(string(in.StartTime))
	}
	{
		const prefix string = ",\"end_time\":"
		out.RawString(prefix)
		out.String(string(in.EndTime))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v WorkInterval) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1c21b86fEncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WorkInterval) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1c21b86fEncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WorkInterval) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1c21b86fDecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WorkInterval) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1c21b86fDecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto1(l, v)
}
func easyjson1c21b86fDecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto2(in *jlexer.Lexer, out *ReplaceWorkIntervalsForDateRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "date":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Date = string(in.String())
			}
		case "intervals":
			if in.IsNull() {
				in.Skip()
				out.Intervals = nil
			} else {
				in.Delim('[')
				if out.Intervals == nil {
					if !in.IsDelim(']') {
						out.Intervals = make([]IntervalInput, 0, 2)
					} else {
						out.Intervals = []IntervalInput{}
					}
				} else {
					out.Intervals = (out.Intervals)[:0]
				}
				for !in.IsDelim(']') {
					var v4 IntervalInput
					if in.IsNull() {
						in.Skip()
					} else {
						(v4).UnmarshalEasyJSON(in)
					}
					out.Intervals = append(out.Intervals, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1c21b86fEncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto2(out *jwriter.Writer, in ReplaceWorkIntervalsForDateRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"date\":"
		out.RawString(prefix[1:])
		out.String(string(in.Date))
	}
	{
		const prefix string = ",\"intervals\":"
		out.RawString(prefix)
		if in.Intervals == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Intervals {
				if v5 > 0 {
					out.RawByte(',')
				}
				(v6).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ReplaceWorkIntervalsForDateRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1c21b86fEncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ReplaceWorkIntervalsForDateRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1c21b86fEncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ReplaceWorkIntervalsForDateRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1c21b86fDecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ReplaceWorkIntervalsForDateRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1c21b86fDecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto2(l, v)
}
func easyjson1c21b86fDecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto3(in *jlexer.Lexer, out *IntervalInput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "start_time":
			if in.IsNull() {
				in.Skip()
			} else {
				out.StartTime = string(in.String())
			}
		case "end_time":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EndTime = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1c21b86fEncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto3(out *jwriter.Writer, in IntervalInput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"start_time\":"
		out.RawString(prefix[1:])
		out.String(string(in.StartTime))
	}
	{
		const prefix string = ",\"end_time\":"
		out.RawString(prefix)
		out.String(string(in.EndTime))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v IntervalInput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1c21b86fEncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v IntervalInput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1c21b86fEncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *IntervalInput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1c21b86fDecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *IntervalInput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1c21b86fDecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto3(l, v)
}
func easyjson1c21b86fDecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto4(in *jlexer.Lexer, out *CreateWorkIntervalRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "date":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Date = string(in.String())
			}
		case "start_time":
			if in.IsNull() {
				in.Skip()
			} else {
				out.StartTime = string(in.String())
			}
		case "end_time":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EndTime = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1c21b86fEncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto4(out *jwriter.Writer, in CreateWorkIntervalRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"date\":"
		out.RawString(prefix[1:])
		out.String(string(in.Date))
	}
	{
		const prefix string = ",\"start_time\":"
		out.RawString(prefix)
		out.String(string(in.StartTime))
	}
	{
		const prefix string = ",\"end_time\":"
		out.RawString(prefix)
		out.String(string(in.EndTime))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateWorkIntervalRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1c21b86fEncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateWorkIntervalRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1c21b86fEncodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateWorkIntervalRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1c21b86fDecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateWorkIntervalRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1c21b86fDecodeGithubComRBSTeamOkoshkiMicroservicesCoreCatalogDto4(l, v)
}
