// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonB30beec6DecodeGithubComRBSTeamOkoshkiMicroservicesCoreUsersDto(in *jlexer.Lexer, out *UpdateMasterRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "category_id":
			if in.IsNull() {
				in.Skip()
				out.CategoryID = nil
			} else {
				if out.CategoryID == nil {
					out.CategoryID = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.CategoryID = string(in.String())
				}
			}
		case "first_name":
			if in.IsNull() {
				in.Skip()
				out.FirstName = nil
			} else {
				if out.FirstName == nil {
					out.FirstName = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.FirstName = string(in.String())
				}
			}
		case "last_name":
			if in.IsNull() {
				in.Skip()
				out.LastName = nil
			} else {
				if out.LastName == nil {
					out.LastName = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.LastName = string(in.String())
				}
			}
		case "phone":
			if in.IsNull() {
				in.Skip()
				out.Phone = nil
			} else {
				if out.Phone == nil {
					out.Phone = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Phone = string(in.String())
				}
			}
		case "address":
			if in.IsNull() {
				in.Skip()
				out.Address = nil
			} else {
				if out.Address == nil {
					out.Address = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Address = string(in.String())
				}
			}
		case "city":
			if in.IsNull() {
				in.Skip()
				out.City = nil
			} else {
				if out.City == nil {
					out.City = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.City = string(in.String())
				}
			}
		case "bio":
			if in.IsNull() {
				in.Skip()
				out.Bio = nil
			} else {
				if out.Bio == nil {
					out.Bio = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Bio = string(in.String())
				}
			}
		case "timezone":
			if in.IsNull() {
				in.Skip()
				out.Timezone = nil
			} else {
				if out.Timezone == nil {
					out.Timezone = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Timezone = string(in.String())
				}
			}
		case "lat":
			if in.IsNull() {
				in.Skip()
				out.Lat = nil
			} else {
				if out.Lat == nil {
					out.Lat = new(float64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Lat = float64(in.Float64())
				}
			}
		case "lon":
			if in.IsNull() {
				in.Skip()
				out.Lon = nil
			} else {
				if out.Lon == nil {
					out.Lon = new(float64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Lon = float64(in.Float64())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB30beec6EncodeGithubComRBSTeamOkoshkiMicroservicesCoreUsersDto(out *jwriter.Writer, in UpdateMasterRequest) {
	out.RawByte('{')
	first := true
	_ = first
	if in.CategoryID != nil {
		const prefix string = ",\"category_id\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(*in.CategoryID))
	}
	if in.FirstName != nil {
		const prefix string = ",\"first_name\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.FirstName))
	}
	if in.LastName != nil {
		const prefix string = ",\"last_name\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.LastName))
	}
	if in.Phone != nil {
		const prefix string = ",\"phone\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.Phone))
	}
	if in.Address != nil {
		const prefix string = ",\"address\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.Address))
	}
	if in.City != nil {
		const prefix string = ",\"city\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.City))
	}
	if in.Bio != nil {
		const prefix string = ",\"bio\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.Bio))
	}
	if in.Timezone != nil {
		const prefix string = ",\"timezone\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.Timezone))
	}
	if in.Lat != nil {
		const prefix string = ",\"lat\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float64(float64(*in.Lat))
	}
	if in.Lon != nil {
		const prefix string = ",\"lon\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float64(float64(*in.Lon))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UpdateMasterRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB30beec6EncodeGithubComRBSTeamOkoshkiMicroservicesCoreUsersDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UpdateMasterRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB30beec6EncodeGithubComRBSTeamOkoshkiMicroservicesCoreUsersDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UpdateMasterRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB30beec6DecodeGithubComRBSTeamOkoshkiMicroservicesCoreUsersDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UpdateMasterRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB30beec6DecodeGithubComRBSTeamOkoshkiMicroservicesCoreUsersDto(l, v)
}
func easyjsonB30beec6DecodeGithubComRBSTeamOkoshkiMicroservicesCoreUsersDto1(in *jlexer.Lexer, out *RegisterMasterResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = string(in.String())
			}
		case "master_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MasterID = string(in.String())
			}
		case "first_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FirstName = string(in.String())
			}
		case "last_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastName = string(in.String())
			}
		case "role":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Role = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB30beec6EncodeGithubComRBSTeamOkoshkiMicroservicesCoreUsersDto1(out *jwriter.Writer, in RegisterMasterResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.UserID))
	}
	{
		const prefix string = ",\"master_id\":"
		out.RawString(prefix)
		out.String(string(in.MasterID))
	}
	{
		const prefix string = ",\"first_name\":"
		out.RawString(prefix)
		out.String(string(in.FirstName))
	}
	{
		const prefix string = ",\"last_name\":"
		out.RawString(prefix)
		out.String(string(in.LastName))
	}
	{
		const prefix string = ",\"role\":"
		out.RawString(prefix)
		out.String(string(in.Role))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RegisterMasterResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB30beec6EncodeGithubComRBSTeamOkoshkiMicroservicesCoreUsersDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RegisterMasterResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB30beec6EncodeGithubComRBSTeamOkoshkiMicroservicesCoreUsersDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RegisterMasterResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB30beec6DecodeGithubComRBSTeamOkoshkiMicroservicesCoreUsersDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RegisterMasterResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB30beec6DecodeGithubComRBSTeamOkoshkiMicroservicesCoreUsersDto1(l, v)
}
func easyjsonB30beec6DecodeGithubComRBSTeamOkoshkiMicroservicesCoreUsersDto2(in *jlexer.Lexer, out *RegisterMasterRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "email":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Email = string(in.String())
			}
		case "password":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Password = string(in.String())
			}
		case "category_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CategoryID = string(in.String())
			}
		case "first_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FirstName = string(in.String())
			}
		case "last_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastName = string(in.String())
			}
		case "phone":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Phone = string(in.String())
			}
		case "address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		case "city":
			if in.IsNull() {
				in.Skip()
			} else {
				out.City = string(in.String())
			}
		case "bio":
			if in.IsNull() {
				in.Skip()
				out.Bio = nil
			} else {
				if out.Bio == nil {
					out.Bio = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Bio = string(in.String())
				}
			}
		case "timezone":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Timezone = string(in.String())
			}
		case "lat":
			if in.IsNull() {
				in.Skip()
				out.Lat = nil
			} else {
				if out.Lat == nil {
					out.Lat = new(float64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Lat = float64(in.Float64())
				}
			}
		case "lon":
			if in.IsNull() {
				in.Skip()
				out.Lon = nil
			} else {
				if out.Lon == nil {
					out.Lon = new(float64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Lon = float64(in.Float64())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB30beec6EncodeGithubComRBSTeamOkoshkiMicroservicesCoreUsersDto2(out *jwriter.Writer, in RegisterMasterRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix[1:])
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"password\":"
		out.RawString(prefix)
		out.String(string(in.Password))
	}
	{
		const prefix string = ",\"category_id\":"
		out.RawString(prefix)
		out.String(string(in.CategoryID))
	}
	{
		const prefix string = ",\"first_name\":"
		out.RawString(prefix)
		out.String(string(in.FirstName))
	}
	{
		const prefix string = ",\"last_name\":"
		out.RawString(prefix)
		out.String(string(in.LastName))
	}
	{
		const prefix string = ",\"phone\":"
		out.RawString(prefix)
		out.String(string(in.Phone))
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"city\":"
		out.RawString(prefix)
		out.String(string(in.City))
	}
	if in.Bio != nil {
		const prefix string = ",\"bio\":"
		out.RawString(prefix)
		out.String(string(*in.Bio))
	}
	if in.Timezone != "" {
		const prefix string = ",\"timezone\":"
		out.RawString(prefix)
		out.String(string(in.Timezone))
	}
	if in.Lat != nil {
		const prefix string = ",\"lat\":"
		out.RawString(prefix)
		out.Float64(float64(*in.Lat))
	}
	if in.Lon != nil {
		const prefix string = ",\"lon\":"
		out.RawString(prefix)
		out.Float64(float64(*in.Lon))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RegisterMasterRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB30beec6EncodeGithubComRBSTeamOkoshkiMicroservicesCoreUsersDto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RegisterMasterRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB30beec6EncodeGithubComRBSTeamOkoshkiMicroservicesCoreUsersDto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RegisterMasterRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB30beec6DecodeGithubComRBSTeamOkoshkiMicroservicesCoreUsersDto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RegisterMasterRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB30beec6DecodeGithubComRBSTeamOkoshkiMicroservicesCoreUsersDto2(l, v)
}
func easyjsonB30beec6DecodeGithubComRBSTeamOkoshkiMicroservicesCoreUsersDto3(in *jlexer.Lexer, out *Master) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = string(in.String())
			}
		case "category_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CategoryID = string(in.String())
			}
		case "first_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FirstName = string(in.String())
			}
		case "last_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastName = string(in.String())
			}
		case "phone":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Phone = string(in.String())
			}
		case "address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		case "city":
			if in.IsNull() {
				in.Skip()
			} else {
				out.City = string(in.String())
			}
		case "bio":
			if in.IsNull() {
				in.Skip()
				out.Bio = nil
			} else {
				if out.Bio == nil {
					out.Bio = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Bio = string(in.String())
				}
			}
		case "avatar_url":
			if in.IsNull() {
				in.Skip()
				out.AvatarURL = nil
			} else {
				if out.AvatarURL == nil {
					out.AvatarURL = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.AvatarURL = string(in.String())
				}
			}
		case "timezone":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Timezone = string(in.String())
			}
		case "lat":
			if in.IsNull() {
				in.Skip()
				out.Lat = nil
			} else {
				if out.Lat == nil {
					out.Lat = new(float64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Lat = float64(in.Float64())
				}
			}
		case "lon":
			if in.IsNull() {
				in.Skip()
				out.Lon = nil
			} else {
				if out.Lon == nil {
					out.Lon = new(float64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Lon = float64(in.Float64())
				}
			}
		case "rating":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Rating = float64(in.Float64())
			}
		case "review_count":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ReviewCount = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB30beec6EncodeGithubComRBSTeamOkoshkiMicroservicesCoreUsersDto3(out *jwriter.Writer, in Master) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix)
		out.String(string(in.UserID))
	}
	{
		const prefix string = ",\"category_id\":"
		out.RawString(prefix)
		out.String(string(in.CategoryID))
	}
	{
		const prefix string = ",\"first_name\":"
		out.RawString(prefix)
		out.String(string(in.FirstName))
	}
	{
		const prefix string = ",\"last_name\":"
		out.RawString(prefix)
		out.String(string(in.LastName))
	}
	{
		const prefix string = ",\"phone\":"
		out.RawString(prefix)
		out.String(string(in.Phone))
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"city\":"
		out.RawString(prefix)
		out.String(string(in.City))
	}
	if in.Bio != nil {
		const prefix string = ",\"bio\":"
		out.RawString(prefix)
		out.String(string(*in.Bio))
	}
	if in.AvatarURL != nil {
		const prefix string = ",\"avatar_url\":"
		out.RawString(prefix)
		out.String(string(*in.AvatarURL))
	}
	{
		const prefix string = ",\"timezone\":"
		out.RawString(prefix)
		out.String(string(in.Timezone))
	}
	if in.Lat != nil {
		const prefix string = ",\"lat\":"
		out.RawString(prefix)
		out.Float64(float64(*in.Lat))
	}
	if in.Lon != nil {
		const prefix string = ",\"lon\":"
		out.RawString(prefix)
		out.Float64(float64(*in.Lon))
	}
	{
		const prefix string = ",\"rating\":"
		out.RawString(prefix)
		out.Float64(float64(in.Rating))
	}
	{
		const prefix string = ",\"review_count\":"
		out.RawString(prefix)
		out.Int(int(in.ReviewCount))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Master) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB30beec6EncodeGithubComRBSTeamOkoshkiMicroservicesCoreUsersDto3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Master) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB30beec6EncodeGithubComRBSTeamOkoshkiMicroservicesCoreUsersDto3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Master) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB30beec6DecodeGithubComRBSTeamOkoshkiMicroservicesCoreUsersDto3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Master) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB30beec6DecodeGithubComRBSTeamOkoshkiMicroservicesCoreUsersDto3(l, v)
}
func easyjsonB30beec6DecodeGithubComRBSTeamOkoshkiMicroservicesCoreUsersDto4(in *jlexer.Lexer, out *CreateMasterRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "category_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CategoryID = string(in.String())
			}
		case "first_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FirstName = string(in.String())
			}
		case "last_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastName = string(in.String())
			}
		case "phone":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Phone = string(in.String())
			}
		case "address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		case "city":
			if in.IsNull() {
				in.Skip()
			} else {
				out.City = string(in.String())
			}
		case "bio":
			if in.IsNull() {
				in.Skip()
				out.Bio = nil
			} else {
				if out.Bio == nil {
					out.Bio = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Bio = string(in.String())
				}
			}
		case "timezone":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Timezone = string(in.String())
			}
		case "lat":
			if in.IsNull() {
				in.Skip()
				out.Lat = nil
			} else {
				if out.Lat == nil {
					out.Lat = new(float64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Lat = float64(in.Float64())
				}
			}
		case "lon":
			if in.IsNull() {
				in.Skip()
				out.Lon = nil
			} else {
				if out.Lon == nil {
					out.Lon = new(float64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Lon = float64(in.Float64())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB30beec6EncodeGithubComRBSTeamOkoshkiMicroservicesCoreUsersDto4(out *jwriter.Writer, in CreateMasterRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"category_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.CategoryID))
	}
	{
		const prefix string = ",\"first_name\":"
		out.RawString(prefix)
		out.String(string(in.FirstName))
	}
	{
		const prefix string = ",\"last_name\":"
		out.RawString(prefix)
		out.String(string(in.LastName))
	}
	{
		const prefix string = ",\"phone\":"
		out.RawString(prefix)
		out.String(string(in.Phone))
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"city\":"
		out.RawString(prefix)
		out.String(string(in.City))
	}
	if in.Bio != nil {
		const prefix string = ",\"bio\":"
		out.RawString(prefix)
		out.String(string(*in.Bio))
	}
	if in.Timezone != "" {
		const prefix string = ",\"timezone\":"
		out.RawString(prefix)
		out.String(string(in.Timezone))
	}
	if in.Lat != nil {
		const prefix string = ",\"lat\":"
		out.RawString(prefix)
		out.Float64(float64(*in.Lat))
	}
	if in.Lon != nil {
		const prefix string = ",\"lon\":"
		out.RawString(prefix)
		out.Float64(float64(*in.Lon))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateMasterRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB30beec6EncodeGithubComRBSTeamOkoshkiMicroservicesCoreUsersDto4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateMasterRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB30beec6EncodeGithubComRBSTeamOkoshkiMicroservicesCoreUsersDto4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateMasterRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB30beec6DecodeGithubComRBSTeamOkoshkiMicroservicesCoreUsersDto4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateMasterRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB30beec6DecodeGithubComRBSTeamOkoshkiMicroservicesCoreUsersDto4(l, v)
}
